const REGIONS={北海道:["北海道"],東北:["青森県","岩手県","宮城県","秋田県","山形県","福島県"],関東:["茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県"],中部:["新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県"],近畿:["三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県"],中国:["鳥取県","島根県","岡山県","広島県","山口県"],四国:["徳島県","香川県","愛媛県","高知県"],九州:["福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県"],沖縄:["沖縄県"]};
const W={0:["快晴","☀️"],1:["晴れ","🌤️"],2:["一部くもり","⛅"],3:["くもり","☁️"],45:["霧","🌫️"],48:["霧氷","🌫️"],51:["弱い霧雨","🌦️"],53:["霧雨","🌦️"],55:["強い霧雨","🌧️"],61:["弱い雨","🌦️"],63:["雨","🌧️"],65:["強い雨","🌧️"],71:["弱い雪","🌨️"],73:["雪","🌨️"],75:["強い雪","❄️"],80:["弱いにわか雨","🌦️"],81:["にわか雨","🌧️"],82:["激しいにわか雨","⛈️"],95:["雷雨","⛈️"],96:["雷雨・ひょう","⛈️"],99:["激しい雷雨・ひょう","⛈️"]};
const $=s=>document.querySelector(s), cn=c=>c.city+(c.ward||""), wm=n=>W[n]||["不明","—"]; let prefs=[],weather=null,currentCity=null,currentPref=null;
const setStatus=(s,load=false)=>{$("#status").textContent=s;$("#status-dot").className=load?"pulse":"dot"};
const distance=(lat,lng,p)=>Math.hypot(lat-p[1],(lng-p[0])*Math.cos(lat*Math.PI/180));
function fill(select,items,value){select.innerHTML=items.map(x=>`<option${x===value?' selected':''}>${x}</option>`).join("")}
function setRegion(name,prefName,cityName){fill($("#region"),Object.keys(REGIONS),name);const ps=prefs.filter(p=>REGIONS[name].includes(p.pref));fill($("#pref"),ps.map(p=>p.pref),prefName);const p=ps.find(x=>x.pref===(prefName||ps[0].pref));setPref(p,cityName)}
function setPref(p,cityName){currentPref=p;const c=p.cities.find(x=>cn(x)===cityName)||p.cities[0];fill($("#city"),p.cities.map(cn),cn(c));selectCity(c,false)}
function selectCity(c,useExact=false,coords){currentCity=c;$("#place").textContent=`${currentPref.pref} ${cn(c)}`;const pos=coords||{lat:c.point[1],lng:c.point[0]};loadWeather(pos.lat,pos.lng);setStatus(useExact?"現在地周辺の情報を表示しています":"選択した地域の情報を表示しています",true)}
function nearest(lat,lng){let best=null;prefs.forEach(p=>p.cities.forEach(c=>{const d=distance(lat,lng,c.point);if(!best||d<best.d)best={p,c,d}}));const r=Object.keys(REGIONS).find(r=>REGIONS[r].includes(best.p.pref));currentPref=best.p;setRegion(r,best.p.pref,cn(best.c));selectCity(best.c,true,{lat,lng})}
function fallback(){const p=prefs.find(x=>x.pref==="静岡県")||prefs[0],c=p.cities.find(x=>cn(x).includes("浜松市中央区"))||p.cities[0];currentPref=p;setRegion("中部",p.pref,cn(c));setStatus("現在地を取得できないため、地域選択の初期値を表示しています",true)}
async function loadWeather(lat,lng){$("#content").classList.add("busy");try{const q=new URLSearchParams({latitude:lat,longitude:lng,hourly:"temperature_2m,relative_humidity_2m,precipitation_probability,weather_code",timezone:"Asia/Tokyo",past_days:1,forecast_days:1,models:"best_match"});const r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}`);if(!r.ok)throw Error();weather=await r.json();$("#updated").textContent=new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date);render();setStatus($("#status").textContent.replace("しています","しています"),false)}catch(e){setStatus("天気情報を取得できませんでした。通信状態をご確認ください");$("#content").innerHTML='<div class="loading-card">天気情報を取得できませんでした</div>'}finally{$("#content").classList.remove("busy")}}
function day(offset,title,kind){const d=new Date;d.setDate(d.getDate()+offset);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;const h=weather.hourly,idx=h.time.map((t,i)=>({t,i})).filter(x=>x.t.startsWith(key)&&+x.t.slice(11,13)>=7&&+x.t.slice(11,13)<=19);const ts=idx.map(x=>h.temperature_2m[x.i]),hs=idx.map(x=>h.relative_humidity_2m[x.i]),rs=idx.map(x=>h.precipitation_probability[x.i]),codes=idx.map(x=>h.weather_code[x.i]);const dom=[...codes].sort((a,b)=>codes.filter(v=>v===a).length-codes.filter(v=>v===b).length).pop()||0;const cells=fn=>idx.map(fn).join("");return `<section class="weather-section ${kind}"><div class="section-head"><div><span class="eyebrow">${kind==='result'?'YESTERDAY':'TODAY'}</span><h2>${title}</h2></div><span class="date-label">${new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(d)}</span></div><div class="weather-grid"><article class="daily-card"><div class="big-icon">${wm(dom)[1]}</div><strong>${wm(dom)[0]}</strong><div class="temp-range"><b>${Math.round(Math.max(...ts))}°</b><span>/ ${Math.round(Math.min(...ts))}°</span></div><dl><div><dt>最大降水確率</dt><dd>${Math.max(...rs)}%</dd></div><div><dt>平均湿度</dt><dd>${Math.round(hs.reduce((a,b)=>a+b,0)/hs.length)}%</dd></div></dl></article><div class="hourly-scroll"><table><thead><tr><th>時刻</th>${cells(x=>`<th>${+x.t.slice(11,13)}時</th>`)}</tr></thead><tbody><tr><th>天気</th>${cells(x=>`<td><span class="icon">${wm(h.weather_code[x.i])[1]}</span><small>${wm(h.weather_code[x.i])[0]}</small></td>`)}</tr><tr><th>降水確率</th>${cells(x=>`<td>${h.precipitation_probability[x.i]}<small>%</small></td>`)}</tr><tr><th>気温</th>${cells(x=>`<td class="temperature">${Math.round(h.temperature_2m[x.i])}<small>°C</small></td>`)}</tr><tr><th>湿度</th>${cells(x=>`<td>${h.relative_humidity_2m[x.i]}<small>%</small></td>`)}</tr></tbody></table></div></div></section>`}
function render(){$("#content").innerHTML=day(-1,"昨日の結果","result")+day(0,"本日の予報","forecast")}
$("#region").onchange=e=>setRegion(e.target.value);$("#pref").onchange=e=>setPref(prefs.find(p=>p.pref===e.target.value));$("#city").onchange=e=>selectCity(currentPref.cities.find(c=>cn(c)===e.target.value));$("#locate").onclick=()=>{setStatus("現在地を確認しています…",true);navigator.geolocation.getCurrentPosition(p=>nearest(p.coords.latitude,p.coords.longitude),()=>setStatus("現在地を取得できませんでした。端末の位置情報設定をご確認ください"),{timeout:8000})};
(async()=>{try{const r=await fetch("https://japanese-addresses-v2.geoloniamaps.com/api/ja.json");if(!r.ok)throw Error();prefs=(await r.json()).data;navigator.geolocation.getCurrentPosition(p=>nearest(p.coords.latitude,p.coords.longitude),fallback,{timeout:8000,maximumAge:600000})}catch(e){setStatus("地域一覧を取得できませんでした。通信状態をご確認ください");$("#content").innerHTML='<div class="loading-card">地域一覧を取得できませんでした</div>'}})();
